### PR TITLE
update to lit@2.0.0-rc.1

### PR DESCRIPTION
**Pull request by mmcnl**
update lit and npm packages

see https://lit.dev/docs/releases/upgrade/ for more info

### CODE REVIEW

**Comment by jbuckner** [comment]
How come you're upgrading to the RC version?

**Comment by mmcnl** [comment]
@jbuckner Because I wanted to see what it would take to upgrade to the new 2.0 format and the RC is the latest current version.

**Comment by jbuckner** [comment]
Cool yeah it looks like it wasn't too bad! I'm hesitant to upgrade to non-final "core" library releases like this for putting things in production. I don't think there will be bugs, but that's what RCs are for. It also becomes more difficult to do versioning. You lose semantic versioning when you specify a version like `-rc.1` so if we start any other `lit` packages, these versions will have to match.

**Comment by mmcnl** [comment]
@jbuckner Since this component isn't currently used anywhere in production, my plan was to do this upgrade now to test the new lit version out and then upgrade to the latest version (which will possibly be the 2.0 stable branch) before we integrate into petabox. Would you rather we don't merge this PR until after lit 2.0 stable is released?

**Comment by jbuckner** [comment]
Yeah I'd prefer to wait for the final version to put it into production. You should still be able to do all the integration work independently and just merge when it's out.

**Comment by mmcnl** [comment]
OK sounds good. I'll keep this PR as a draft for reference and then do the petabox integration work in another branch :)

**Pull request closed without merging**
